### ISSUE TITLE
Explore covid dialogflow bot made by Google

### ISSUE THREAD

**Issue by konishon** [hawa-ko-reporter/hawa-ko-reporter.github.io#4]
## Tasks
- [ ] Setup on personal account
- [ ] Give Access to nishon@naxa.com.np
- [ ] Find out how they are doing follow-up questions to conduct a survey.
- [ ] Find out are they doing something different in intents and entities that we don't know.
